{{- if .Values.authz.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-config
  labels:
    app: authz
data:
  config.yaml: |
    # grpc server
    grpc:
      port: 9011

      {{- if .Values.certManager.enabled }}
      enableTLS: true
      certFile: /etc/tls/authz/tls.crt
      keyFile: /etc/tls/authz/tls.key
      {{- else }}
      enableTLS: false
      {{- end }}

      # JWT required claims for authentication
      authEnabled: {{ .Values.authEnabled }}
      audience: authz

      allowed:
        - serviceAccount: ssh-proxy
        - serviceAccount: provisioner
        - serviceAccount: api-server
        - serviceAccount: identity

    # JWT verifier configuration for token validation
    jwtVerifier:
      signingMethod: ${JWT_SIGNING_METHOD}
      privateKeyFile: /run/secrets/jwt-issuer/private-key.pem

    policy:
      directory: /app/policies
      default: |
        {{- .Values.authz.defaultPolicy | nindent 8 }}

    nats:
      enabled: {{ .Values.nats.enabled }}
      url: nats://{{ .Values.nats.host }}:{{ .Values.nats.port }}
      username: {{ .Values.nats.username }}
      password: ${NATS_K8SHELL_PASSWORD}

    # Identity service configuration
    identity:
      address: identity:9020
      tokenFilePath: /var/run/secrets/k8shell.io/identity
      {{- if .Values.certManager.enabled }}
      caCertPath: /etc/k8shell/ca/ca.crt
      serverName: identity.{{ .Release.Namespace }}.svc
      {{- end }}

    enrichment:
      user:
        timeout: {{ .Values.authz.enrichment.user.timeout }}
        cacheTTL: {{ .Values.authz.enrichment.user.cacheTTL }}

    db:
      enabled: {{ .Values.postgresql.enabled }}
      database: {{ .Values.postgresql.database }}
      hostname: {{ .Values.postgresql.host }}
      port: {{ .Values.postgresql.port }}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}

    audit:
      retention: {{ .Values.authz.audit.retention }}
      bufferSize: {{ .Values.authz.audit.bufferSize }}
      flushInterval: {{ .Values.authz.audit.flushInterval }}

{{- end }}
