apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-base-files
data:
  base.yaml: |
{{ .Files.Get "files/blueprints/base.yaml" | indent 4 }}
{{- if .Values.provisioner.includeBlueprintSamples }}
  samples.yaml: |
{{ .Files.Get "files/blueprints/samples.yaml" | indent 4 }}
{{- end }}
