{{- if .Values.provisioner.injectNamespaces }}
{{- range .Values.provisioner.injectNamespaces }}
{{- $injectNamespace := . }}
{{- $provisionerNamespace := $.Release.Namespace }}
{{- $nameSuffix := printf "%s-%s" $provisionerNamespace $injectNamespace | sha256sum | trunc 8 }}
{{- $roleName := printf "provisioner-inject-%s-%s" ($provisionerNamespace | trunc 20 | trimSuffix "-") $nameSuffix }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  namespace: {{ $injectNamespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "create", "update", "delete", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName }}
  namespace: {{ $injectNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName }}
subjects:
- kind: ServiceAccount
  name: provisioner
  namespace: {{ $provisionerNamespace }}
{{- end }}
{{- end }}