{{- $secrets := dict -}}
{{- if .Values.provisioner.privateRegistry.enabled -}}
{{- $registrySecrets := dict
  "PRIVATE_REGISTRY_HOST" .Values.provisioner.privateRegistry.host.value
  "PRIVATE_REGISTRY_USERNAME" .Values.provisioner.privateRegistry.username.value
  "PRIVATE_REGISTRY_PASSWORD" .Values.provisioner.privateRegistry.password.value
-}}
{{- range $key, $value := $registrySecrets }}
{{- if $value }}
  {{- $_ := set $secrets $key $value }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.provisioner.privateRegistry.cert.value }}
  {{- $_ := set $secrets "regcert.pem" . }}
{{- end }}

{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: int-provisioner
type: Opaque
data:
{{ include "k8shell.secretData" $secrets | nindent 2 }}
{{- end }}
