apiVersion: v1
kind: ConfigMap
metadata:
  name: worktrace-detector-rules
  labels:
    app: worktrace-detector
data:
  {{- if .Values.rules.includeDefaults }}
  {{- range $path, $bytes := .Files.Glob "files/rules/*.yaml" }}
  {{ base $path }}: |-
    {{- $bytes | toString | trim | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- range $name, $content := .Values.rules.extra }}
  {{ $name }}: |-
    {{- $content | trim | nindent 4 }}
  {{- end }}
  {{- if and (not .Values.rules.includeDefaults) (not .Values.rules.extra) }}
  dummy.yaml: ""
  {{- end }}
