apiVersion: v1
kind: Service
metadata:
  name: worktrace-controller
  labels:
    {{- include "worktrace-detector.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  {{- if and .Values.grpc .Values.grpc.roundRobin }}
  clusterIP: None
  {{- end }}
  ports:
    - port: 9050
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    k8shell.io/app: worktrace-detector-controller
