{{- if .Values.frontend.enabled }}
{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-tls
  duration: {{ .Values.certManager.duration }}
  renewBefore: {{ .Values.certManager.renewBefore }}
  commonName: {{ .Values.frontend.host }}
  dnsNames:
    - {{ .Values.frontend.host }}
    - "*.{{ .Values.frontend.host }}"
  usages:
    - server auth
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: {{ .Values.certManager.issuer.kind }}
{{- end }}
{{- end }}