{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "k8shell.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8101
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8shell.io/app: frontend
{{- end }}