apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8shell-secrets
  namespace: {{ .Values.targetNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    chart: {{ .Values.charts.vaultSecrets.chartName }}
    repoURL: {{ .Values.charts.vaultSecrets.repoURL }}
    targetRevision: {{ .Values.charts.vaultSecrets.chartVersion }}
    helm:
      valuesObject: 
        vaultAddress: {{ .Values.vault.address }} 
        roleName: {{ .Values.vault.roleName }}
        serviceAccount: vault-sa
        secrets:
          - name: vault-ssh
            path: "{{ .Values.vault.pathPrefix }}/ssh"
          - name: vault-jwt
            path: "{{ .Values.vault.pathPrefix }}/jwt"
          - name: vault-db
            path: "{{ .Values.vault.pathPrefix }}/db"
          {{- if .Values.idpGithub.enabled }}
          - name: vault-github
            path: "{{ .Values.vault.pathPrefix }}/github"
          {{- end }}
          {{- if .Values.idpGitlab.enabled }}
          - name: vault-gitlab
            path: "{{ .Values.vault.pathPrefix }}/gitlab"
          {{- end }}
          {{- if .Values.sshShield.enabled }}
          - name: vault-nfgate
            path: "{{ .Values.vault.pathPrefix }}/nfgate"
          {{- end }}
          - name: vault-nats
            path: "{{ .Values.vault.pathPrefix }}/nats"
          - name: vault-private-registry
            path: "{{ .Values.vault.pathPrefix }}/registry"
          - name: regcred
            path: "{{ .Values.vault.pathPrefix }}/registry"
            type: dockerconfigjson
            dockerConfigMapping:
              registryKey: "ADDRESS"
              usernameKey: "USERNAME"
              passwordKey: "PASSWORD"      
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.targetNamespace }}
  {{- include "k8shell-bundle.syncPolicy" (dict "root" .) | nindent 2 }}
