{{- if .Values.nats.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nats-external
  {{- if .Values.nats.loadBalancer.annotations }}
  annotations:
    {{- toYaml .Values.nats.loadBalancer.annotations | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
  ports:
    - name: nats
      port: {{ .Values.nats.loadBalancer.port }}
      targetPort: nats
      protocol: TCP
{{- end }}