apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8shell.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity