{{- $secrets := dict -}}
{{- if .Values.postgresql.enabled -}}
{{- $postgresSecrets := dict
  "POSTGRES_USERNAME" .Values.postgresql.username.value
  "POSTGRES_PASSWORD" .Values.postgresql.password.value
-}}
{{- range $key, $value := $postgresSecrets }}
{{- if $value }}
  {{- $_ := set $secrets $key $value }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.identity.smtp.enabled }}
{{- if .Values.identity.smtp.password.value }}
  {{- $_ := set $secrets "SMTP_PASSWORD" .Values.identity.smtp.password.value }}
{{- end }}
{{- end }}

{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: int-identity
type: Opaque
data:
{{ include "k8shell.secretData" $secrets | nindent 2 }}
{{- end }}
