{{- $secrets := dict -}}
{{- if .Values.postgresql.enabled -}}
{{- $postgresSecrets := dict
  "POSTGRES_USERNAME" .Values.postgresql.username.value
  "POSTGRES_PASSWORD" .Values.postgresql.password.value
-}}
{{- range $key, $value := $postgresSecrets }}
{{- if $value }}
  {{- $_ := set $secrets $key $value }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.identity.smtp.enabled -}}
{{- $smtpSecrets := dict
  "SMTP_HOST" .Values.identity.smtp.host.value
  "SMTP_PORT" .Values.identity.smtp.port.value
  "SMTP_USERNAME" .Values.identity.smtp.username.value
  "SMTP_PASSWORD" .Values.identity.smtp.password.value
  "SMTP_FROM" .Values.identity.smtp.from.value
-}}
{{- range $key, $value := $smtpSecrets }}
{{- if $value }}
  {{- $_ := set $secrets $key $value }}
{{- end }}
{{- end }}
{{- end }}

{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: int-identity
type: Opaque
data:
{{ include "k8shell.secretData" $secrets | nindent 2 }}
{{- end }}
