{{- if .Values.vaultConnection.create }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Values.vaultConnection.name }}
spec:
  address: {{ .Values.vaultAddress }}
  skipTLSVerify: true
{{- end }}
