{{- range .Values.secrets }}
{{- $pathParts := regexSplit "/" .path -1 }}
{{- $mount := index $pathParts 0 }}    
{{- $secretPath := slice $pathParts 1 (len $pathParts) }}    

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
spec:
  vaultAuthRef: vault-auth
  mount: {{ $mount }}   
  path: {{ join "/" $secretPath }}   
  type: kv-v1
  destination:
    name: {{ .name }}
    create: true
    {{- if eq .type "dockerconfigjson" }}
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        ".dockerconfigjson":
          text: |
            {{`{{- with .Secrets }}`}}
              {{`{{- $config := mustDeepCopy . -}}`}}
              {{`{{- $hostname := get $config "`}}{{ .dockerConfigMapping.registryKey }}{{`" -}}`}}
              {{`{{- $_ := unset $config "`}}{{ .dockerConfigMapping.registryKey }}{{`" -}}`}}
              {{`{{- $_ := unset $config "`}}{{ .dockerConfigMapping.usernameKey }}{{`" -}}`}}
              {{`{{- $_ := unset $config "`}}{{ .dockerConfigMapping.passwordKey }}{{`" -}}`}}
              {{`{{- $_ := set $config "username" (get . "`}}{{ .dockerConfigMapping.usernameKey }}{{`") -}}`}}
              {{`{{- $_ := set $config "password" (get . "`}}{{ .dockerConfigMapping.passwordKey }}{{`") -}}`}}
              {{`{{- $_ := set $config "auth" (list (get . "`}}{{ .dockerConfigMapping.usernameKey }}{{`") ":" (get . "`}}{{ .dockerConfigMapping.passwordKey }}{{`") | join "" | b64enc) -}}`}}
              {{`{{- dict "auths" (dict $hostname $config) | mustToJson -}}`}}
            {{`{{- end }}`}}
    {{- end }}
---
{{- end }}

