{{- if .Values.vaultAuth.create }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vaultAuth.name }}
spec:
  vaultConnectionRef: {{ .Values.vaultConnection.name }}
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Values.roleName }}
    serviceAccount: {{ .Values.serviceAccount }}
{{- end }}
