apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-proxy-config
  labels:
    app: ssh-proxy
data:
  config.yaml: |
    server:
      port: 2022
      serverKey: /app/secrets/server_key

      forking: true
      proxyProtocol: {{ .Values.sshProxy.proxyProtocol }}

      {{- with .Values.sshProxy.writerOptions }}
      writerOptions:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.sshProxy.publishSshFailures }}
      publishSshFailures:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # enable/disable session recording per stream type
      # requires session to be configured
      recording:
        {{- $pvc := .Values.session.recording.persistentVolumeClaim.install }}
        {{- $rec := .Values.sshProxy.recording }}
        recordShell: {{ and $rec.recordShell $pvc }}
        recordExec: {{ and $rec.recordExec $pvc }}
        recordDirectTCPIP: {{ and $rec.recordDirectTCPIP $pvc }}

    nats:
      enabled: {{ .Values.nats.enabled }}
      url: nats://{{ .Values.nats.host }}:{{ .Values.nats.port }}
      username: {{ .Values.nats.username }}
      password: ${NATS_K8SHELL_PASSWORD}

    # Identity service configuration
    identity:
      address: identity:9020
      tokenFilePath: /var/run/secrets/k8shell.io/identity
      {{- if .Values.certManager.enabled }}
      caCertPath: /etc/k8shell/ca/ca.crt
      serverName: identity.{{ .Release.Namespace }}.svc
      {{- end }}

    {{- if .Values.session.enabled }}
    # Session service configuration
    session:
      address: session:9010
      tokenFilePath: /var/run/secrets/k8shell.io/session
      {{- if .Values.certManager.enabled }}
      caCertPath: /etc/k8shell/ca/ca.crt
      serverName: session.{{ .Release.Namespace }}.svc
      {{- end }}
    {{- end }}

    # Provisioner service configuration
    provisioner:
      address: provisioner:9030
      tokenFilePath: /var/run/secrets/k8shell.io/provisioner
      {{- if .Values.certManager.enabled }}
      caCertPath: /etc/k8shell/ca/ca.crt
      serverName: provisioner.{{ .Release.Namespace }}.svc
      {{- end }}

    # worksspace client configuration
    k8shelld:
      tokenFilePath: /var/run/secrets/k8shell.io/k8shelld

