blueprints:
  - name: base
    description: Base template for all workspaces. 
    isTemplate: true

    splash: |
      Welcome to k8shell - cloud-native workspaces on Kubernetes!
      Connected to k8shelld (version: {{.Version}}-{{.Commit}})
      For more information, visit https://k8shell.io

    image: docker.io/alpine:latest
    imagePullPolicy: IfNotPresent

    subdomain: !cel "user.organization"
    hostname: !cel "user.username + '-' + metadata.name"

    k8shelld:
      image: !cel env("DEFAULT_K8SHELLD_IMAGE")
      imagePullPolicy: IfNotPresent
      ignoreOrphans:
        - .*JetBrains.*

    network:
      networkPolicyClass: workspace

    resources:
      cpu: 4
      memory: 4Gi

    podman:
      enabled: false
      image: quay.io/podman/stable:v5.8.1

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        appArmorProfile:
          type: Unconfined

      resources:
        cpu: 2
        memory: 2Gi

      # use the same volumes as in the main workspace
      parentStorages: true

      createDockerSockSymlink: true

    # Podman with mount point working setup
    # it is possible to mount a volume in a workspace into the podman container and read/write the data in the folder
    # podman:
    #   enabled: true
    #   extFiles:
    #     /etc/containers/containers.conf: |
    #       [containers]
    #       netns="host"
    #       userns="host"
    #       ipcns="host"
    #       utsns="host"
    #       cgroupns="host"
    #       cgroups="disabled"
    #       log_driver = "k8s-file"
    #       volumes = ["/proc:/proc"]
    #       default_sysctls = []
    #       [engine]
    #       cgroup_manager = "cgroupfs"
    #       events_logger="file"
    #       runtime="crun"
    #     /etc/containers/storage.conf: |
    #       [storage]
    #       driver = "overlay"
    #       rootless_storage_path = "/home/podman/storage"
    #     /etc/group: !cel "'root:x:0:\\n' + user.username + ':x:' + string(user.gid) + ':\\n'"
    #     /etc/passwd: !cel "'root:x:0:0:root:/root:/bin/sh\\n' + user.username + ':x:' + string(user.uid) + ':' + string(user.gid) + '::/home/podman:/bin/sh\\n'"
    #     /etc/subgid: !cel user.username + ':2000000000:65536'
    #     /etc/subuid: !cel user.username + ':2000000000:65536'
    #   securityContext:
    #     appArmorProfile:
    #       type: Unconfined
    #     runAsGroup: !cel user.gid
    #     runAsUser: !cel user.uid
    #   storages:
    #     graphdb:
    #       claimSpec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 10Gi
    #         storageClassName: openebs-zfspv
    #       enabled: true
    #       path: /home/podman
    #       readonly: false


    # list of storages in the workspace
    # storages:
    #   home:
    #     enabled: false
    #     storageClass: ""
    #     size: 10Gi
    #     path: !cel "'/home/' + user.username"
    #     readonly: False

    enableApps: false
    apps:
      vscode:
        enabled: false
        listen: 8080
        installAsRoot: true
        binary: "/usr/bin/code-server"
        versionCmd: ["/usr/bin/code-server", "--version"]
        versionRegex: "^([0-9]+\\.[0-9]+\\.[0-9]+)"
        install: |
          curl -fsSL https://code-server.dev/install.sh | sh
        start: ["/usr/bin/code-server", "--auth=none", "--bind-addr=127.0.0.1:8080", "$HOME"]
        restartPolicy: always
        protocol: "http"
