apiVersion: v1
kind: ServiceAccount
metadata:
  name: idp-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "idp-github.labels" . | nindent 4 }}
    app.kubernetes.io/component: idp-github
