apiVersion: v1
kind: Service
metadata:
  name: idp-github
  labels:
    {{- include "idp-github.labels" . | nindent 4 }}
    app.kubernetes.io/component: idp-github
spec:
  type: ClusterIP
  {{- if and .Values.grpc .Values.grpc.roundRobin }}
  clusterIP: None
  {{- end }}
  ports:
    - port: 9030
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    k8shell.io/app: idp-github
