name: Build vault-secrets chart

on:
  push:
    branches:
      - "main"
    paths:
      - "vault-secrets/*"

jobs:
  vault-secrets-chart:
    runs-on: k8shell-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package helm chart
        run: |
          mkdir -p dist
          helm package vault-secrets -d dist/
          helm registry login ${{ secrets.REGISTRY }} --username "${{ secrets.HARBOR_USER }}" \
            --password "${{ secrets.HARBOR_PASSWORD }}"
          helm push dist/$(ls dist | grep tgz) oci://${{ secrets.REGISTRY }}/charts
